# Generated by Django 2.0.3 on 2018-03-11 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aircraft_type', models.TextField()),
                ('weight', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_code', models.CharField(max_length=3)),
                ('airport_name', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(decimal_places=1, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(decimal_places=1, max_digits=9)),
                ('identifier', models.TextField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turb.Aircraft')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dest', to='turb.Airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='turb.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.DecimalField(decimal_places=1, max_digits=9)),
                ('wind_x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('wind_y', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tke', models.DecimalField(decimal_places=4, max_digits=6)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turb.Flight')),
            ],
        ),
    ]
