# Generated by Django 2.0.2 on 2018-02-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherreport',
            name='acceleration',
        ),
        migrations.RemoveField(
            model_name='weatherreport',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weatherreport',
            name='wind_vector',
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_name',
            field=models.TextField(default='airport'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='altitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='tke',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='wind_x',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherreport',
            name='wind_y',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='airport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weatherreport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
