# Generated by Django 2.0.2 on 2018-02-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turb', '0002_auto_20180217_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherreport',
            name='altitude',
            field=models.DecimalField(decimal_places=1, max_digits=9),
        ),
        migrations.AlterField(
            model_name='weatherreport',
            name='tke',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='weatherreport',
            name='wind_x',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='weatherreport',
            name='wind_y',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
