# Generated by Django 2.0.4 on 2018-04-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turb', '0003_flight_bearing'),
        ('turb', '0002_auto_20180401_1549'),
    ]

    operations = [
    ]
