# Generated by Django 2.0.4 on 2018-04-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turb', '0004_merge_20180414_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
